name: Basic Deploy PHP to Windows Server

on:
  push:
    branches:
      - main
      - taller-git

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Windows Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "Remove-Item -Recurse -Force C:\inetpub\wwwroot\*"
          scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:C:\inetpub\wwwroot
